services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - landlord_db_data:/var/lib/postgresql/data

  backend:
    image: node:18
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - '.:/app'
    ports:
      - "${API_PORT-5001}:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    restart: on-failure


volumes:
  landlord_db_data:
